name: MLOps CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.11 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name : Run Data Preprocessing Tests
        run: |
          python src/data/run_processing.py  \
          --input data/raw/house_data.csv  \
          --output data/processed/cleaned_house_data_v1.csv

      - name : Run Feature Engineering Tests
        run: |
          python src/features/engineer.py  \
          --input data/processed/final_data.csv  \
          --output data/processed/featured_house_data.csv   \
          --preprocessor models/trained/preprocessor.pkl

      # - name : Run Model Training Tests
      #   run: |
      #     python src/models/train_model.py  \
      #     --config configs/model_config.yaml  \
      #     --input data/processed/featured_house_data.csv  \
      #     --output models/trained/house_rent_model.pkl

