name: MLOps CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
   workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.11 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name : Run Data Preprocessing Tests
        run: |
          python src/data/run_processing.py  \
          --input data/raw/data.csv  \
          --output data/processed/cleaned_house_data_v1.csv

      - name : Run Feature Engineering Tests
        run: |
          python src/features/engineer.py  \
          --input data/processed/final_data.csv  \
          --output data/processed/featured_house_data.csv   \
          --preprocessor models/trained/preprocessor.pkl

      - name : Setup MLFLow (Docker)
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d -p 5555:5000 --name mlflow-server ghcr.io/mlflow/mlflow:latest \
          mlflow server --host 0.0.0.0 --backend-store-uri \ 
          sqlite:///mlflow.db --default-artifact-root /tmp/mlruns

      - name : Run Model Training Tests
        run: |
          python src/models/train_model.py  \
          --config configs/model_config.yaml \
          --data data/processed/featured_house_data.csv \
          --models-dir models \
          --mlflow-tracking-uri http://localhost:5555

      - name : Cleaning up MLFlow
        run: |
          docker stop mlflow-server
          docker rm mlflow-server
          docker rmi ghcr.io/mlflow/mlflow:latest