name: MLOps CI Workflow 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  workflow:
    runs-on: ubuntu-latest

    services:
      mlflow:
        image: ghcr.io/mlflow/mlflow:latest
        ports:
          - 5555:5000
        options: >-
          --health-cmd "curl -f http://localhost:5000/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          MLFLOW_BACKEND_STORE_URI: sqlite:////tmp/mlflow.db
          MLFLOW_DEFAULT_ARTIFACT_ROOT: /tmp/mlruns

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.11 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Data Preprocessing Tests
        run: |
          python src/data/run_processing.py  \
          --input data/raw/data.csv  \
          --output data/processed/cleaned_house_data_v1.csv

      - name: Run Feature Engineering Tests
        run: |
          python src/features/engineer.py  \
          --input data/processed/final_data.csv  \
          --output data/processed/featured_house_data.csv   \
          --preprocessor models/trained/preprocessor.pkl

      - name: Wait for MLflow to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5555/health > /dev/null; then
              echo "MLflow server is ready!"
              break
            fi
            echo "Waiting for MLflow... ($i/30)"
            sleep 2
          done

      - name: Run Model Training Tests
        env:
          MLFLOW_TRACKING_URI: http://localhost:5555
        run: |
          python src/models/train_model.py  \
            --config configs/model_config.yaml \
            --data data/processed/featured_house_data.csv \
            --models-dir models \
            --mlflow-tracking-uri http://localhost:5555